<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Analysis</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Proposal.html">Proposal</a>
</li>
<li>
  <a href="introduction.html">Introduction</a>
</li>
<li>
  <a href="data.html">Data Description</a>
</li>
<li>
  <a href="eda.html">Plot Results</a>
</li>
<li>
  <a href="analysis.html">Analysis</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="discussion.html">Discussion</a>
</li>
<li>
  <a href="https://github.com/Yaxuan-Z111/p8105_final_project.github.io.git">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Analysis</h1>

</div>


<pre class="r"><code>source(here(&quot;data&quot;, &quot;datacleaning.R&quot;))</code></pre>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This analysis aims to investigate factors associated with the
likelihood of being diagnosed with diabetes (DIBEV_A) using a
multivariable logistic regression model. Covariates include demographic,
lifestyle, physical health, and chronic disease indicators.</p>
</div>
<div id="methodology" class="section level1">
<h1>Methodology</h1>
<p>The outcome variable, <code>DIBEV_A</code>, is a binary indicator
representing whether an individual has been diagnosed with diabetes (0 =
No diabetes, 1 = Diabetes diagnosis). Given the binary nature of the
outcome, a logistic regression model within the Generalized Linear Model
(GLM) framework was employed. Logistic regression is appropriate for
modeling the probability of an event occurring while ensuring predicted
probabilities remain between 0 and 1, using a logit link to relate the
linear combination of predictors to the log-odds of the outcome.</p>
<p>Covariates in the model include demographic factors (e.g., sex and
age), anthropometric measures (weight and height), lifestyle indicators,
and a range of chronic disease or health status variables. Categorical
variables, including BMI category, educational attainment, and various
health event indicators, were encoded as factors to allow estimation of
separate effects for each non-reference level. Continuous variables such
as age, weight, and height were included directly.</p>
<p>The logistic regression model can be formally expressed as:</p>
<p><span class="math display">\[
\text{Logit}(P(\text{DIBEV_A}=1)) = \beta_0
+ \sum_{i=1}^{20} \beta_i X_i
\]</span></p>
<p>where <span class="math inline">\(X_i\)</span> represents each
covariate, including both categorical indicator variables and continuous
predictors, and <span class="math inline">\(\beta_i\)</span> denotes the
corresponding log-odds coefficient. Exponentiating the coefficients
yields odds ratios, which provide a clinically interpretable measure of
the relative likelihood of diabetes associated with each predictor,
conditional on all other variables in the model.</p>
<p>The outcome variable, DIBEV_A, is coded as a binary factor (0 = No
diabetes, 1 = Diabetes diagnosis). Several categorical predictors are
converted to factor type, and continuous variables such as age, height,
and weight are included directly. A logistic regression model with a
logit link is fitted.</p>
<p>The original detailed model :</p>
<p><span class="math display">\[
\text{Logit}(P(\text{DIBEV_A}=1)) =
\log\left(\frac{P(\text{DIBEV_A}=1)}{1-P(\text{DIBEV_A}=1)}\right) =
\beta_0 \\
+ \beta_1 \cdot \text{SEX_A} + \beta_2 \cdot \text{AGEP_A} + \beta_3
\cdot \text{BMICATD_A} + \beta_4 \cdot \text{WEIGHTLBTC_A} + \beta_5
\cdot \text{HEIGHTTC_A} \\
+ \beta_6 \cdot \text{DIFF_A} + \beta_7 \cdot \text{EDUCP_A} + \beta_8
\cdot \text{LSATIS4_A} + \beta_9 \cdot \text{PHSTAT_A} + \beta_{10}
\cdot \text{CHLEV_A} \\
+ \beta_{11} \cdot \text{HYPEV_A} + \beta_{12} \cdot \text{LIVEREV_A} +
\beta_{13} \cdot \text{STREV_A} + \beta_{14} \cdot \text{MIEV_A} +
\beta_{15} \cdot \text{ANGEV_A} \\
+ \beta_{16} \cdot \text{CHDEV_A} + \beta_{17} \cdot \text{DEPEV_A} +
\beta_{18} \cdot \text{ANXEV_A} + \beta_{19} \cdot \text{SMKEV_A} +
\beta_{20} \cdot \text{LONELY_A}
\]</span></p>
</div>
<div id="build-model" class="section level1">
<h1>Build Model</h1>
<pre class="r"><code>df_model = 
  nhis24_df_fit |&gt;
  mutate(
    # Outcome: DIBEV_A
    DIBEV_A = factor(DIBEV_A, levels = c(0, 1)),
    
    # Covariates - Dichotomous/Ordinal/Categorical (MUST be factor)
    SEX_A = factor(SEX_A), # Assume 1/2 coding is acceptable
    BMICATD_A = factor(BMICATD_A), # Codes 0, 1, 2, 3
    DIFF_A = factor(DIFF_A), # Codes 0, 1, 2, 3
    EDUCP_A = factor(EDUCP_A), # Codes 0, 1, 2
    LSATIS4_A = factor(LSATIS4_A), # Codes 0, 1
    PHSTAT_A = factor(PHSTAT_A), # Codes 0, 1
    CHLEV_A = factor(CHLEV_A), # Codes 0, 1
    HYPEV_A = factor(HYPEV_A), # Codes 0, 1
    LIVEREV_A = factor(LIVEREV_A), # Codes 0, 1
    STREV_A = factor(STREV_A), # Codes 0, 1
    MIEV_A = factor(MIEV_A), # Codes 0, 1
    ANGEV_A = factor(ANGEV_A), # Codes 0, 1
    CHDEV_A = factor(CHDEV_A), # Codes 0, 1
    DEPEV_A = factor(DEPEV_A), # Codes 0, 1
    ANXEV_A = factor(ANXEV_A), # Codes 0, 1
    SMKEV_A = factor(SMKEV_A), # Codes 0, 1
    LONELY_A = factor(LONELY_A) # Codes 0, 1, 2, 3, 4
  ) </code></pre>
<pre class="r"><code>model_formula &lt;- DIBEV_A ~ SEX_A + AGEP_A + BMICATD_A + WEIGHTLBTC_A + HEIGHTTC_A + 
                           DIFF_A + EDUCP_A + LSATIS4_A + PHSTAT_A + CHLEV_A + 
                           HYPEV_A + LIVEREV_A + STREV_A + MIEV_A + ANGEV_A + 
                           CHDEV_A + DEPEV_A + ANXEV_A + SMKEV_A + LONELY_A

glm_model &lt;- glm(
  model_formula, 
  data = df_model,
  family = binomial(link = &quot;logit&quot;)
)

summary(glm_model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = model_formula, family = binomial(link = &quot;logit&quot;), 
##     data = df_model)
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -3.3804123  0.5948181  -5.683 1.32e-08 ***
## SEX_A1        0.2679901  0.0622719   4.304 1.68e-05 ***
## AGEP_A        0.0212543  0.0019510  10.894  &lt; 2e-16 ***
## BMICATD_A1   -1.1100671  0.3522212  -3.152  0.00162 ** 
## BMICATD_A2    0.5043795  0.0659413   7.649 2.03e-14 ***
## BMICATD_A3    0.9985941  0.0693331  14.403  &lt; 2e-16 ***
## WEIGHTLBTC_A  0.0012410  0.0003787   3.277  0.00105 ** 
## HEIGHTTC_A   -0.0288851  0.0096941  -2.980  0.00289 ** 
## DIFF_A1       0.1613321  0.0555216   2.906  0.00366 ** 
## DIFF_A2       0.3171973  0.0766891   4.136 3.53e-05 ***
## DIFF_A3       0.2415579  0.1393943   1.733  0.08311 .  
## EDUCP_A1     -0.1094541  0.0523165  -2.092  0.03642 *  
## EDUCP_A2     -0.3220990  0.0548189  -5.876 4.21e-09 ***
## LSATIS4_A1   -0.1229233  0.0976854  -1.258  0.20826    
## PHSTAT_A1     0.6949544  0.0532801  13.043  &lt; 2e-16 ***
## CHLEV_A1      0.7451109  0.0469785  15.861  &lt; 2e-16 ***
## HYPEV_A1      0.7553104  0.0513709  14.703  &lt; 2e-16 ***
## LIVEREV_A1    0.6563458  0.1354417   4.846 1.26e-06 ***
## STREV_A1      0.1061399  0.0827067   1.283  0.19938    
## MIEV_A1       0.2843106  0.0876442   3.244  0.00118 ** 
## ANGEV_A1      0.0081820  0.1125910   0.073  0.94207    
## CHDEV_A1      0.2292477  0.0733358   3.126  0.00177 ** 
## DEPEV_A1      0.1614773  0.0644540   2.505  0.01223 *  
## ANXEV_A1     -0.0823857  0.0666432  -1.236  0.21638    
## SMKEV_A1     -0.0874370  0.0452642  -1.932  0.05340 .  
## LONELY_A1     0.0409552  0.0547341   0.748  0.45431    
## LONELY_A2     0.0683829  0.0577379   1.184  0.23627    
## LONELY_A3    -0.1803688  0.1416713  -1.273  0.20297    
## LONELY_A4     0.1505242  0.1238934   1.215  0.22439    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 17357  on 23625  degrees of freedom
## Residual deviance: 14423  on 23597  degrees of freedom
## AIC: 14481
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<div id="histogram-of-p-value" class="section level2">
<h2>histogram of P-value</h2>
<pre class="r"><code>glm_summary = summary(glm_model)

p_values_df = data.frame(
  Variable = rownames(glm_summary$coefficients),
  P_value = glm_summary$coefficients[, &quot;Pr(&gt;|z|)&quot;]
)

# Remove intercept
p_values_df = 
  p_values_df[p_values_df$Variable != &quot;(Intercept)&quot;, ]

P_value_hisg =
  p_values_df|&gt;
  ggplot(aes(x = reorder(Variable, P_value), y = P_value)) +
  geom_bar(
    stat = &quot;identity&quot;,
    fill = ifelse(p_values_df$P_value &lt; 0.05, &quot;red&quot;, &quot;skyblue&quot;)
  ) +
  geom_hline(yintercept = 0.05, linetype = &quot;dashed&quot;, color = &quot;black&quot;) +
  coord_flip() +
  labs(
    title = &quot;P-values from Logistic Regression&quot;,
    x = &quot;Variables&quot;,
    y = &quot;P-value&quot;
  ) +
  theme_minimal()

P_value_hisg</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
</div>
<div id="model-results" class="section level1">
<h1>Model Results</h1>
<p>Tidy results.</p>
<pre class="r"><code>tidy_logit &lt;- function(model) {
  broom::tidy(model, conf.int = TRUE) |&gt;
    mutate(
      Beta     = estimate,
      OR       = exp(estimate),
      Lower_CI = exp(conf.low),
      Upper_CI = exp(conf.high),
      p.value  = format.pval(p.value, digits = 3, eps = 0.001)
    ) |&gt;
    select(term, Beta, OR, Lower_CI, Upper_CI, p.value)
}</code></pre>
<p>Clean up term names for presentation.</p>
<pre class="r"><code>clean_term_labels &lt;- function(df) {
  df |&gt;
    mutate(
      term = gsub(&quot;`&quot;, &quot;&quot;, term),
      Term = case_when(
        term == &quot;(Intercept)&quot; ~ &quot;Intercept&quot;,
        term == &quot;SEX_A2&quot; ~ &quot;SEX_A: Female (vs Male)&quot;,
        
        # BMI (0: Healthy Weight)
        term == &quot;BMICATD_A1&quot; ~ &quot;BMICATD_A: Underweight (vs Healthy)&quot;,
        term == &quot;BMICATD_A2&quot; ~ &quot;BMICATD_A: Overweight (vs Healthy)&quot;,
        term == &quot;BMICATD_A3&quot; ~ &quot;BMICATD_A: Obese (vs Healthy)&quot;,
        
        # Difficulty Walking (0: No Difficulty)
        term == &quot;DIFF_A1&quot; ~ &quot;DIFF_A: Some Difficulty (vs No Difficulty)&quot;,
        term == &quot;DIFF_A2&quot; ~ &quot;DIFF_A: A lot of Difficulty (vs No Difficulty)&quot;,
        term == &quot;DIFF_A3&quot; ~ &quot;DIFF_A: Cannot do (vs No Difficulty)&quot;,
        
        # Education (0: Low Education)
        term == &quot;EDUCP_A1&quot; ~ &quot;EDUCP_A: Medium Edu (vs Low Edu)&quot;,
        term == &quot;EDUCP_A2&quot; ~ &quot;EDUCP_A: High Edu (vs Low Edu)&quot;,
        
        # Life Satisfaction (0: Satisfied/Very Satisfied)
        term == &quot;LSATIS4_A1&quot; ~ &quot;LSATIS4_A: Dissatisfied (vs Satisfied)&quot;,
        
        # Health Status (0: Good/VGood/Excellent Health)
        term == &quot;PHSTAT_A1&quot; ~ &quot;PHSTAT_A: Fair/Poor Health (vs Good Health)&quot;,
        
        # Loneliness (0: Never Lonely)
        term == &quot;LONELY_A1&quot; ~ &quot;LONELY_A: Rarely Lonely (vs Never Lonely)&quot;,
        term == &quot;LONELY_A2&quot; ~ &quot;LONELY_A: Sometimes Lonely (vs Never Lonely)&quot;,
        term == &quot;LONELY_A3&quot; ~ &quot;LONELY_A: Usually Lonely (vs Never Lonely)&quot;,
        term == &quot;LONELY_A4&quot; ~ &quot;LONELY_A: Always Lonely (vs Never Lonely)&quot;,
        
        # Chronic Dichotomous Conditions (1: Yes vs 0: No)
        term == &quot;CHLEV_A1&quot; ~ &quot;CHLEV_A: High Cholesterol (Yes)&quot;,
        term == &quot;HYPEV_A1&quot; ~ &quot;HYPEV_A: Hypertension (Yes)&quot;,
        term == &quot;LIVEREV_A1&quot; ~ &quot;LIVEREV_A: Liver Disease (Yes)&quot;,
        term == &quot;STREV_A1&quot; ~ &quot;STREV_A: Stroke (Yes)&quot;,
        term == &quot;MIEV_A1&quot; ~ &quot;MIEV_A: Myocardial Infarction (Yes)&quot;,
        term == &quot;ANGEV_A1&quot; ~ &quot;ANGEV_A: Angina (Yes)&quot;,
        term == &quot;CHDEV_A1&quot; ~ &quot;CHDEV_A: CHD (Yes)&quot;,
        term == &quot;DEPEV_A1&quot; ~ &quot;DEPEV_A: Depression (Yes)&quot;,
        term == &quot;ANXEV_A1&quot; ~ &quot;ANXEV_A: Anxiety (Yes)&quot;,
        term == &quot;SMKEV_A1&quot; ~ &quot;SMKEV_A: Smoker (Yes)&quot;,
        
        # Continuous Variables
        term == &quot;AGEP_A&quot; ~ &quot;AGEP_A (Per Year)&quot;,
        term == &quot;WEIGHTLBTC_A&quot; ~ &quot;WEIGHTLBTC_A (Per lb)&quot;,
        term == &quot;HEIGHTTC_A&quot; ~ &quot;HEIGHTTC_A (Per unit)&quot;,
        
        TRUE ~ term
      )
    ) |&gt;
    select(Term, Beta, OR, Lower_CI, Upper_CI, p.value)
}</code></pre>
<p>Generate kable table.</p>
<pre class="r"><code>format_logit_table &lt;- function(df,
                               caption,
                               footnote_text = &quot;Reference Outcome: No Diabetes (DIBEV_A = 0).&quot;) {
  df |&gt;
    dplyr::mutate(
      OR_CI = paste0(
        round(OR, 3), &quot; (&quot;,
        round(Lower_CI, 3), &quot; - &quot;,
        round(Upper_CI, 3), &quot;)&quot;
      ),
      Beta = round(Beta, 4)
    ) |&gt;
    dplyr::select(Term, Beta, OR_CI, p.value) |&gt;
    knitr::kable(
      caption   = caption,
      col.names = c(&quot;Predictor Term&quot;, &quot;Coefficient (Beta)&quot;, &quot;Adjusted OR (95% CI)&quot;, &quot;P-value&quot;),
      align     = c(&quot;l&quot;, &quot;r&quot;, &quot;r&quot;, &quot;r&quot;),
      booktabs  = TRUE
    ) |&gt;
    kableExtra::kable_styling(
      full_width    = TRUE,
      position      = &quot;left&quot;,
      latex_options = &quot;hold_position&quot;
    ) |&gt;
    kableExtra::add_header_above(c(&quot; &quot; = 2, &quot;Odds Ratio&quot; = 1, &quot; &quot; = 1)) |&gt;
    kableExtra::footnote(
      general        = footnote_text,
      threeparttable = TRUE
    )
}</code></pre>
<pre class="r"><code>model_results_tidy = 
  glm_model |&gt;
  tidy_logit() |&gt;
  clean_term_labels()

model_results_tidy |&gt; 
  format_logit_table(
    caption = &quot;Multivariable Logistic Regression of Diabetes Diagnosis (Adjusted Odds Ratios)&quot;
  )</code></pre>
<table class="table" style="border-bottom: 0;">
<caption>
Multivariable Logistic Regression of Diabetes Diagnosis (Adjusted Odds
Ratios)
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Odds Ratio
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:left;">
Predictor Term
</th>
<th style="text-align:right;">
Coefficient (Beta)
</th>
<th style="text-align:right;">
Adjusted OR (95% CI)
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Intercept
</td>
<td style="text-align:right;">
-3.3804
</td>
<td style="text-align:right;">
0.034 (0.011 - 0.109)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
SEX_A1
</td>
<td style="text-align:right;">
0.2680
</td>
<td style="text-align:right;">
1.307 (1.157 - 1.477)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
AGEP_A (Per Year)
</td>
<td style="text-align:right;">
0.0213
</td>
<td style="text-align:right;">
1.021 (1.018 - 1.025)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
BMICATD_A: Underweight (vs Healthy)
</td>
<td style="text-align:right;">
-1.1101
</td>
<td style="text-align:right;">
0.33 (0.154 - 0.621)
</td>
<td style="text-align:right;">
0.00162
</td>
</tr>
<tr>
<td style="text-align:left;">
BMICATD_A: Overweight (vs Healthy)
</td>
<td style="text-align:right;">
0.5044
</td>
<td style="text-align:right;">
1.656 (1.456 - 1.886)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
BMICATD_A: Obese (vs Healthy)
</td>
<td style="text-align:right;">
0.9986
</td>
<td style="text-align:right;">
2.714 (2.371 - 3.112)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
WEIGHTLBTC_A (Per lb)
</td>
<td style="text-align:right;">
0.0012
</td>
<td style="text-align:right;">
1.001 (1 - 1.002)
</td>
<td style="text-align:right;">
0.00105
</td>
</tr>
<tr>
<td style="text-align:left;">
HEIGHTTC_A (Per unit)
</td>
<td style="text-align:right;">
-0.0289
</td>
<td style="text-align:right;">
0.972 (0.953 - 0.99)
</td>
<td style="text-align:right;">
0.00289
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: Some Difficulty (vs No Difficulty)
</td>
<td style="text-align:right;">
0.1613
</td>
<td style="text-align:right;">
1.175 (1.054 - 1.31)
</td>
<td style="text-align:right;">
0.00366
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: A lot of Difficulty (vs No Difficulty)
</td>
<td style="text-align:right;">
0.3172
</td>
<td style="text-align:right;">
1.373 (1.181 - 1.595)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: Cannot do (vs No Difficulty)
</td>
<td style="text-align:right;">
0.2416
</td>
<td style="text-align:right;">
1.273 (0.965 - 1.668)
</td>
<td style="text-align:right;">
0.08311
</td>
</tr>
<tr>
<td style="text-align:left;">
EDUCP_A: Medium Edu (vs Low Edu)
</td>
<td style="text-align:right;">
-0.1095
</td>
<td style="text-align:right;">
0.896 (0.809 - 0.993)
</td>
<td style="text-align:right;">
0.03642
</td>
</tr>
<tr>
<td style="text-align:left;">
EDUCP_A: High Edu (vs Low Edu)
</td>
<td style="text-align:right;">
-0.3221
</td>
<td style="text-align:right;">
0.725 (0.651 - 0.807)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
LSATIS4_A: Dissatisfied (vs Satisfied)
</td>
<td style="text-align:right;">
-0.1229
</td>
<td style="text-align:right;">
0.884 (0.729 - 1.069)
</td>
<td style="text-align:right;">
0.20826
</td>
</tr>
<tr>
<td style="text-align:left;">
PHSTAT_A: Fair/Poor Health (vs Good Health)
</td>
<td style="text-align:right;">
0.6950
</td>
<td style="text-align:right;">
2.004 (1.805 - 2.224)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
CHLEV_A: High Cholesterol (Yes)
</td>
<td style="text-align:right;">
0.7451
</td>
<td style="text-align:right;">
2.107 (1.922 - 2.31)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
HYPEV_A: Hypertension (Yes)
</td>
<td style="text-align:right;">
0.7553
</td>
<td style="text-align:right;">
2.128 (1.925 - 2.355)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
LIVEREV_A: Liver Disease (Yes)
</td>
<td style="text-align:right;">
0.6563
</td>
<td style="text-align:right;">
1.928 (1.474 - 2.508)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
STREV_A: Stroke (Yes)
</td>
<td style="text-align:right;">
0.1061
</td>
<td style="text-align:right;">
1.112 (0.944 - 1.306)
</td>
<td style="text-align:right;">
0.19938
</td>
</tr>
<tr>
<td style="text-align:left;">
MIEV_A: Myocardial Infarction (Yes)
</td>
<td style="text-align:right;">
0.2843
</td>
<td style="text-align:right;">
1.329 (1.118 - 1.577)
</td>
<td style="text-align:right;">
0.00118
</td>
</tr>
<tr>
<td style="text-align:left;">
ANGEV_A: Angina (Yes)
</td>
<td style="text-align:right;">
0.0082
</td>
<td style="text-align:right;">
1.008 (0.807 - 1.255)
</td>
<td style="text-align:right;">
0.94207
</td>
</tr>
<tr>
<td style="text-align:left;">
CHDEV_A: CHD (Yes)
</td>
<td style="text-align:right;">
0.2292
</td>
<td style="text-align:right;">
1.258 (1.089 - 1.451)
</td>
<td style="text-align:right;">
0.00177
</td>
</tr>
<tr>
<td style="text-align:left;">
DEPEV_A: Depression (Yes)
</td>
<td style="text-align:right;">
0.1615
</td>
<td style="text-align:right;">
1.175 (1.035 - 1.333)
</td>
<td style="text-align:right;">
0.01223
</td>
</tr>
<tr>
<td style="text-align:left;">
ANXEV_A: Anxiety (Yes)
</td>
<td style="text-align:right;">
-0.0824
</td>
<td style="text-align:right;">
0.921 (0.808 - 1.049)
</td>
<td style="text-align:right;">
0.21638
</td>
</tr>
<tr>
<td style="text-align:left;">
SMKEV_A: Smoker (Yes)
</td>
<td style="text-align:right;">
-0.0874
</td>
<td style="text-align:right;">
0.916 (0.838 - 1.001)
</td>
<td style="text-align:right;">
0.05340
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Rarely Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
0.0410
</td>
<td style="text-align:right;">
1.042 (0.936 - 1.159)
</td>
<td style="text-align:right;">
0.45431
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Sometimes Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
0.0684
</td>
<td style="text-align:right;">
1.071 (0.956 - 1.199)
</td>
<td style="text-align:right;">
0.23627
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Usually Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
-0.1804
</td>
<td style="text-align:right;">
0.835 (0.629 - 1.096)
</td>
<td style="text-align:right;">
0.20297
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Always Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
0.1505
</td>
<td style="text-align:right;">
1.162 (0.909 - 1.477)
</td>
<td style="text-align:right;">
0.22439
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Reference Outcome: No Diabetes (DIBEV_A = 0).
</td>
</tr>
</tfoot>
</table>
</div>
<div id="forest-results" class="section level1">
<h1>Forest Results</h1>
<p>First of all, we filter out terms that are very close to 1 with wide
CIs and non-significant to reduce clutter. Secondly, we order the terms
for better visualization, e.g., by OR value.</p>
<pre class="r"><code>forest_data = 
  model_results_tidy |&gt;
  filter(Term != &quot;Intercept&quot;) |&gt;
  mutate(Term = fct_reorder(Term, OR, .desc = TRUE)) 

forest_plots = 
ggplot(forest_data, aes(x = OR, y = Term)) +
  geom_vline(xintercept = 1, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  geom_pointrange(aes(xmin = Lower_CI, xmax = Upper_CI), size = 0.3) +
  scale_x_log10(breaks = c(0.1, 0.2, 0.5, 1, 2, 5, 10),
                labels = c(&quot;0.1&quot;, &quot;0.2&quot;, &quot;0.5&quot;, &quot;1&quot;, &quot;2&quot;, &quot;5&quot;, &quot;10&quot;)) + 
  labs(
    title = &quot;Forest Plot of Adjusted Odds Ratios for Diabetes Diagnosis&quot;,
    x = &quot;Adjusted Odds Ratio (log scale)&quot;,
    y = &quot;Predictor Term&quot;
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = &quot;bold&quot;),
    axis.text.y = element_text(size = 9, face = &quot;bold&quot;),
    axis.title.x = element_text(size = 10, face = &quot;bold&quot;),
    axis.title.y = element_text(size = 10, face = &quot;bold&quot;),
    panel.grid.minor.x = element_blank() # Remove minor grid lines on x-axis
  )

print(forest_plots)</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>This forest plot displays adjusted odds ratios (ORs) for diabetes
diagnosis, where the y-axis lists predictors (with reference groups in
parentheses), and the x-axis (log scale) shows ORs (dashed red line at
OR=1, no association). Based on the plots, we used the 95% confidence
interval (CI) exclusion of 1 as the measure of statistical significance,
several variables demonstrated a significant independent association
with a diabetes diagnosis. Predictors with OR &lt; 1 and 95% CIs not
crossing 1 (e.g., underweight BMI, higher education, lower loneliness,
smoking, anxiety) are linked to lower diabetes risk; those with OR &gt;
1 and significant CIs (e.g., overweight/obese BMI, liver disease,
fair/poor health, high cholesterol, hypertension) increase risk; and
factors like stroke history, severe mobility difficulty, and some
loneliness categories have CIs crossing 1, showing no significant
association.</p>
<p>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD</p>
<p>======= # Interpretation of Model Coefficients</p>
<p>Below is the interpretation of the logistic regression output, with
each variable summarized under its own subsection.</p>
<hr />
<div id="sex" class="section level3">
<h3>Sex</h3>
<div id="male-vs-female" class="section level4">
<h4>Male vs Female</h4>
<ul>
<li>Coefficient β = –0.4402<br />
</li>
<li>OR = 0.644 (95% CI: 0.602–0.688), <em>p</em> &lt; 0.001</li>
</ul>
<p>Males had significantly lower odds of diabetes compared with females
after adjusting for all covariates.</p>
<hr />
</div>
</div>
<div id="age" class="section level3">
<h3>Age</h3>
<div id="continuous-per-year-increase" class="section level4">
<h4>Continuous (per year increase)</h4>
<ul>
<li>OR = 1.002 (95% CI: 1.000–1.003), <em>p</em> = 0.0156</li>
</ul>
<p>Older age was a small but statistically significant risk factor for
diabetes.</p>
<hr />
</div>
</div>
<div id="smoking" class="section level3">
<h3>Smoking</h3>
<div id="smoker-vs-non-smoker" class="section level4">
<h4>Smoker vs Non-Smoker</h4>
<ul>
<li>OR = 0.916 (95% CI: 0.838–1.001), <em>p</em> = 0.0534</li>
</ul>
<p>Smoking showed a borderline non-significant inverse
association.<br />
There is no strong evidence of an association between smoking and
diabetes in this adjusted model.</p>
<hr />
</div>
</div>
<div id="loneliness" class="section level3">
<h3>Loneliness</h3>
<p>Compared with the “Never Lonely” reference group:</p>
<ul>
<li>Rarely lonely: OR = 1.042, <em>p</em> = 0.4543<br />
</li>
<li>Sometimes lonely: OR = 1.071, <em>p</em> = 0.2363<br />
</li>
<li>Usually lonely: OR = 0.835, <em>p</em> = 0.2029<br />
</li>
<li>Always lonely: OR = 1.162, <em>p</em> = 0.2244</li>
</ul>
<p>None of the loneliness categories were statistically
significant.<br />
Loneliness does not appear to be independently associated with diabetes
risk.</p>
<hr />
</div>
<div id="education" class="section level3">
<h3>Education</h3>
<div id="medium-education-vs-low-education" class="section level4">
<h4>Medium Education vs Low Education</h4>
<ul>
<li>OR = 0.896 (95% CI: 0.809–0.993), <em>p</em> = 0.0364</li>
</ul>
</div>
<div id="high-education-vs-low-education" class="section level4">
<h4>High Education vs Low Education</h4>
<ul>
<li>OR = 0.725 (95% CI: 0.651–0.807), <em>p</em> &lt; 0.001</li>
</ul>
<p>Higher education was protective.<br />
Those with high education had markedly lower odds of diabetes.</p>
<hr />
</div>
</div>
<div id="bmi-category" class="section level3">
<h3>BMI Category</h3>
<p>Reference = BMI category 0 (Normal weight)</p>
<ul>
<li>Underweight: OR = 1.887, <em>p</em> &lt; 0.001<br />
</li>
<li>Overweight: OR = 2.314, <em>p</em> &lt; 0.001<br />
</li>
<li>Obesity (Class I–III): OR = 4.491, <em>p</em> &lt; 0.001</li>
</ul>
<p>BMI demonstrated a strong dose-response relationship, with obesity
being the strongest risk factor in the model.</p>
<hr />
</div>
<div id="difficulty-walking-mobility" class="section level3">
<h3>Difficulty Walking (Mobility)</h3>
<p>Reference = No difficulty</p>
<ul>
<li>Some difficulty: OR = 1.173, <em>p</em> = 0.0037<br />
</li>
<li>A lot of difficulty: OR = 1.373, <em>p</em> &lt; 0.001<br />
</li>
<li>Cannot do at all: OR = 1.273, <em>p</em> = 0.0831</li>
</ul>
<p>Greater mobility limitations were associated with higher odds of
diabetes.</p>
<hr />
</div>
<div id="life-satisfaction" class="section level3">
<h3>Life Satisfaction</h3>
<ul>
<li>Dissatisfied vs satisfied: OR = 0.884, <em>p</em> = 0.2083 → Not
significant</li>
</ul>
<hr />
</div>
<div id="general-health-status" class="section level3">
<h3>General Health Status</h3>
<div id="fairpoor-vs-goodvery-goodexcellent" class="section level4">
<h4>Fair/Poor vs Good/Very Good/Excellent</h4>
<ul>
<li>OR = 2.004 (95% CI: 1.805–2.224), <em>p</em> &lt; 0.001</li>
</ul>
<p>Poor health was a strong predictor of diabetes.</p>
<hr />
</div>
</div>
<div id="high-cholesterol" class="section level3">
<h3>High Cholesterol</h3>
<ul>
<li>OR = 2.107, <em>p</em> &lt; 0.001</li>
</ul>
<p>A strong and significant association.</p>
<hr />
</div>
<div id="hypertension" class="section level3">
<h3>Hypertension</h3>
<ul>
<li>OR = 2.128, <em>p</em> &lt; 0.001</li>
</ul>
<p>Hypertension was one of the largest predictors, more than doubling
the odds of diabetes.</p>
<hr />
</div>
<div id="liver-disease" class="section level3">
<h3>Liver Disease</h3>
<ul>
<li>OR = 1.928, <em>p</em> &lt; 0.001</li>
</ul>
<p>Individuals with liver disease had nearly double the odds of
diabetes.</p>
<hr />
</div>
<div id="stroke" class="section level3">
<h3>Stroke</h3>
<ul>
<li>OR = 1.112, <em>p</em> = 0.199</li>
</ul>
<p>Not statistically significant.</p>
<hr />
</div>
<div id="myocardial-infarction" class="section level3">
<h3>Myocardial Infarction</h3>
<ul>
<li>OR = 1.329 (95% CI: 1.118–1.577), <em>p</em> = 0.0012</li>
</ul>
<p>History of myocardial infarction was positively associated with
diabetes.</p>
<hr />
</div>
<div id="angina" class="section level3">
<h3>Angina</h3>
<ul>
<li>OR = 1.008, <em>p</em> = 0.942</li>
</ul>
<p>No association.</p>
<hr />
</div>
<div id="coronary-heart-disease-chd" class="section level3">
<h3>Coronary Heart Disease (CHD)</h3>
<ul>
<li>OR = 1.258 (95% CI: 1.089–1.451), <em>p</em> = 0.0018</li>
</ul>
<p>CHD was a significant predictor of diabetes.</p>
<hr />
</div>
<div id="depression" class="section level3">
<h3>Depression</h3>
<ul>
<li>OR = 1.175 (95% CI: 1.035–1.333), <em>p</em> = 0.0122</li>
</ul>
<p>Depression was significantly associated with increased diabetes
odds.</p>
<hr />
</div>
<div id="anxiety" class="section level3">
<h3>Anxiety</h3>
<ul>
<li>OR = 0.921 (95% CI: 0.808–1.049), <em>p</em> = 0.216</li>
</ul>
<p>Anxiety was not significantly related to diabetes.</p>
<hr />
</div>
<div id="summary-of-findings" class="section level3">
<h3>Summary of Findings</h3>
<p>Overall, the multivariable logistic regression analysis identifies
several strong predictors of diabetes. Obesity, hypertension, high
cholesterol, liver disease, poor general health, and myocardial
infarction were among the strongest risk factors, each contributing
substantially to elevated diabetes odds. Higher education showed a
consistent protective effect. Mobility limitations were also associated
with greater risk, illustrating the interconnected nature of physical
functioning and metabolic health. While depression was significantly
associated with increased diabetes risk, other psychosocial factors such
as anxiety and loneliness were not significant in this adjusted model.
Smoking likewise showed no significant association. Collectively, these
findings highlight the multifactorial nature of diabetes, involving
biological, behavioral, and socioeconomic determinants.</p>
</div>
</div>
<div id="test-for-confounders" class="section level1">
<h1>Test for confounders</h1>
<p>Build model without confounders.</p>
<pre class="r"><code>model_formula_noconf = DIBEV_A ~ WEIGHTLBTC_A + HEIGHTTC_A + 
                           DIFF_A + LSATIS4_A + PHSTAT_A + CHLEV_A + 
                           HYPEV_A + LIVEREV_A + STREV_A + MIEV_A + ANGEV_A + 
                           CHDEV_A + DEPEV_A + ANXEV_A + SMKEV_A + LONELY_A

glm_model_noconf = glm(
  model_formula_noconf, 
  data = df_model,
  family = binomial(link = &quot;logit&quot;)
)

summary(glm_model_noconf)</code></pre>
<pre><code>## 
## Call:
## glm(formula = model_formula_noconf, family = binomial(link = &quot;logit&quot;), 
##     data = df_model)
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -0.8305458  0.4033405  -2.059 0.039478 *  
## WEIGHTLBTC_A  0.0019753  0.0002656   7.438 1.02e-13 ***
## HEIGHTTC_A   -0.0439723  0.0066774  -6.585 4.54e-11 ***
## DIFF_A1       0.3412926  0.0532778   6.406 1.49e-10 ***
## DIFF_A2       0.5243196  0.0738511   7.100 1.25e-12 ***
## DIFF_A3       0.4421386  0.1352006   3.270 0.001075 ** 
## LSATIS4_A1   -0.1863379  0.0963371  -1.934 0.053085 .  
## PHSTAT_A1     0.7172978  0.0522966  13.716  &lt; 2e-16 ***
## CHLEV_A1      0.8235807  0.0461509  17.845  &lt; 2e-16 ***
## HYPEV_A1      0.9971622  0.0496452  20.086  &lt; 2e-16 ***
## LIVEREV_A1    0.6341245  0.1336490   4.745 2.09e-06 ***
## STREV_A1      0.0919913  0.0817218   1.126 0.260308    
## MIEV_A1       0.3108152  0.0867263   3.584 0.000339 ***
## ANGEV_A1      0.0361691  0.1113181   0.325 0.745244    
## CHDEV_A1      0.3221200  0.0719183   4.479 7.50e-06 ***
## DEPEV_A1      0.1203290  0.0633300   1.900 0.057429 .  
## ANXEV_A1     -0.1859314  0.0650717  -2.857 0.004272 ** 
## SMKEV_A1     -0.0202076  0.0442679  -0.456 0.648041    
## LONELY_A1    -0.0254681  0.0537393  -0.474 0.635557    
## LONELY_A2     0.0152676  0.0568901   0.268 0.788414    
## LONELY_A3    -0.2178835  0.1394693  -1.562 0.118233    
## LONELY_A4     0.1244614  0.1225349   1.016 0.309762    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 17357  on 23625  degrees of freedom
## Residual deviance: 14865  on 23604  degrees of freedom
## AIC: 14909
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Model without confounders result:</p>
<pre class="r"><code>model_results_tidy_noconf =
  glm_model_noconf |&gt;
  tidy_logit() |&gt;
  clean_term_labels() 

model_results_tidy_noconf |&gt; 
  format_logit_table(
    caption = &quot;Multivariable Logistic Regression of Diabetes Diagnosis (Adjusted Odds Ratios) Without Confounders&quot;
  )</code></pre>
<table class="table" style="border-bottom: 0;">
<caption>
Multivariable Logistic Regression of Diabetes Diagnosis (Adjusted Odds
Ratios) Without Confounders
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Odds Ratio
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:left;">
Predictor Term
</th>
<th style="text-align:right;">
Coefficient (Beta)
</th>
<th style="text-align:right;">
Adjusted OR (95% CI)
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Intercept
</td>
<td style="text-align:right;">
-0.8305
</td>
<td style="text-align:right;">
0.436 (0.198 - 0.961)
</td>
<td style="text-align:right;">
0.03948
</td>
</tr>
<tr>
<td style="text-align:left;">
WEIGHTLBTC_A (Per lb)
</td>
<td style="text-align:right;">
0.0020
</td>
<td style="text-align:right;">
1.002 (1.001 - 1.002)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
HEIGHTTC_A (Per unit)
</td>
<td style="text-align:right;">
-0.0440
</td>
<td style="text-align:right;">
0.957 (0.945 - 0.97)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: Some Difficulty (vs No Difficulty)
</td>
<td style="text-align:right;">
0.3413
</td>
<td style="text-align:right;">
1.407 (1.267 - 1.561)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: A lot of Difficulty (vs No Difficulty)
</td>
<td style="text-align:right;">
0.5243
</td>
<td style="text-align:right;">
1.689 (1.461 - 1.951)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: Cannot do (vs No Difficulty)
</td>
<td style="text-align:right;">
0.4421
</td>
<td style="text-align:right;">
1.556 (1.189 - 2.022)
</td>
<td style="text-align:right;">
0.00107
</td>
</tr>
<tr>
<td style="text-align:left;">
LSATIS4_A: Dissatisfied (vs Satisfied)
</td>
<td style="text-align:right;">
-0.1863
</td>
<td style="text-align:right;">
0.83 (0.686 - 1.001)
</td>
<td style="text-align:right;">
0.05309
</td>
</tr>
<tr>
<td style="text-align:left;">
PHSTAT_A: Fair/Poor Health (vs Good Health)
</td>
<td style="text-align:right;">
0.7173
</td>
<td style="text-align:right;">
2.049 (1.849 - 2.27)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
CHLEV_A: High Cholesterol (Yes)
</td>
<td style="text-align:right;">
0.8236
</td>
<td style="text-align:right;">
2.279 (2.082 - 2.495)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
HYPEV_A: Hypertension (Yes)
</td>
<td style="text-align:right;">
0.9972
</td>
<td style="text-align:right;">
2.711 (2.46 - 2.989)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
LIVEREV_A: Liver Disease (Yes)
</td>
<td style="text-align:right;">
0.6341
</td>
<td style="text-align:right;">
1.885 (1.447 - 2.444)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
STREV_A: Stroke (Yes)
</td>
<td style="text-align:right;">
0.0920
</td>
<td style="text-align:right;">
1.096 (0.933 - 1.285)
</td>
<td style="text-align:right;">
0.26031
</td>
</tr>
<tr>
<td style="text-align:left;">
MIEV_A: Myocardial Infarction (Yes)
</td>
<td style="text-align:right;">
0.3108
</td>
<td style="text-align:right;">
1.365 (1.15 - 1.616)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
ANGEV_A: Angina (Yes)
</td>
<td style="text-align:right;">
0.0362
</td>
<td style="text-align:right;">
1.037 (0.832 - 1.287)
</td>
<td style="text-align:right;">
0.74524
</td>
</tr>
<tr>
<td style="text-align:left;">
CHDEV_A: CHD (Yes)
</td>
<td style="text-align:right;">
0.3221
</td>
<td style="text-align:right;">
1.38 (1.198 - 1.588)
</td>
<td style="text-align:right;">
&lt; 0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
DEPEV_A: Depression (Yes)
</td>
<td style="text-align:right;">
0.1203
</td>
<td style="text-align:right;">
1.128 (0.996 - 1.276)
</td>
<td style="text-align:right;">
0.05743
</td>
</tr>
<tr>
<td style="text-align:left;">
ANXEV_A: Anxiety (Yes)
</td>
<td style="text-align:right;">
-0.1859
</td>
<td style="text-align:right;">
0.83 (0.73 - 0.943)
</td>
<td style="text-align:right;">
0.00427
</td>
</tr>
<tr>
<td style="text-align:left;">
SMKEV_A: Smoker (Yes)
</td>
<td style="text-align:right;">
-0.0202
</td>
<td style="text-align:right;">
0.98 (0.898 - 1.069)
</td>
<td style="text-align:right;">
0.64804
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Rarely Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
-0.0255
</td>
<td style="text-align:right;">
0.975 (0.877 - 1.083)
</td>
<td style="text-align:right;">
0.63556
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Sometimes Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
0.0153
</td>
<td style="text-align:right;">
1.015 (0.908 - 1.135)
</td>
<td style="text-align:right;">
0.78841
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Usually Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
-0.2179
</td>
<td style="text-align:right;">
0.804 (0.608 - 1.051)
</td>
<td style="text-align:right;">
0.11823
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Always Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
0.1245
</td>
<td style="text-align:right;">
1.133 (0.888 - 1.435)
</td>
<td style="text-align:right;">
0.30976
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Reference Outcome: No Diabetes (DIBEV_A = 0).
</td>
</tr>
</tfoot>
</table>
<p>Compare with the original data.</p>
<pre class="r"><code>compare_table = 
  model_results_tidy |&gt;
  select(
    Term,
    Beta_full     = Beta,
    OR_full       = OR,
    Lower_full    = Lower_CI,
    Upper_full    = Upper_CI,
    p_full        = p.value
  ) |&gt;
  full_join(
    model_results_tidy_noconf |&gt;
      select(
        Term,
        Beta_noconf  = Beta,
        OR_noconf    = OR,
        Lower_noconf = Lower_CI,
        Upper_noconf = Upper_CI,
        p_noconf     = p.value
      ),
    by = &quot;Term&quot;
  ) |&gt;
  mutate(
    OR_change_pct   = (OR_full - OR_noconf) / OR_noconf * 100,
    Beta_change_pct = (Beta_full - Beta_noconf) / Beta_noconf * 100
  ) |&gt; 
  filter(
    Term != &quot;Intercept&quot;
  )

compare_table |&gt;
  mutate(
    OR_full     = round(OR_full, 3),
    OR_noconf   = round(OR_noconf, 3),
    OR_change_pct = round(OR_change_pct, 1)
  ) |&gt;
  select(
    Term,
    OR_noconf,
    OR_full,
    OR_change_pct
  ) |&gt;
  knitr::kable(
    caption   = &quot;Comparison of Odds Ratios With and Without Prespecified Confounders&quot;,
    col.names = c(
      &quot;Predictor Term&quot;,
      &quot;OR (Model without confounders)&quot;,
      &quot;OR (Full model)&quot;,
      &quot;% Change in OR&quot;
    ),
    align    = c(&quot;l&quot;, &quot;r&quot;, &quot;r&quot;, &quot;r&quot;),
    booktabs = TRUE
  ) |&gt;
  kableExtra::kable_styling(
    full_width    = FALSE,
    position      = &quot;left&quot;,
    latex_options = &quot;hold_position&quot;
  )</code></pre>
<table class="table" style="width: auto !important; ">
<caption>
Comparison of Odds Ratios With and Without Prespecified Confounders
</caption>
<thead>
<tr>
<th style="text-align:left;">
Predictor Term
</th>
<th style="text-align:right;">
OR (Model without confounders)
</th>
<th style="text-align:right;">
OR (Full model)
</th>
<th style="text-align:right;">
% Change in OR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
SEX_A1
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1.307
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
AGEP_A (Per Year)
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1.021
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
BMICATD_A: Underweight (vs Healthy)
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.330
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
BMICATD_A: Overweight (vs Healthy)
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1.656
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
BMICATD_A: Obese (vs Healthy)
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
2.714
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
WEIGHTLBTC_A (Per lb)
</td>
<td style="text-align:right;">
1.002
</td>
<td style="text-align:right;">
1.001
</td>
<td style="text-align:right;">
-0.1
</td>
</tr>
<tr>
<td style="text-align:left;">
HEIGHTTC_A (Per unit)
</td>
<td style="text-align:right;">
0.957
</td>
<td style="text-align:right;">
0.972
</td>
<td style="text-align:right;">
1.5
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: Some Difficulty (vs No Difficulty)
</td>
<td style="text-align:right;">
1.407
</td>
<td style="text-align:right;">
1.175
</td>
<td style="text-align:right;">
-16.5
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: A lot of Difficulty (vs No Difficulty)
</td>
<td style="text-align:right;">
1.689
</td>
<td style="text-align:right;">
1.373
</td>
<td style="text-align:right;">
-18.7
</td>
</tr>
<tr>
<td style="text-align:left;">
DIFF_A: Cannot do (vs No Difficulty)
</td>
<td style="text-align:right;">
1.556
</td>
<td style="text-align:right;">
1.273
</td>
<td style="text-align:right;">
-18.2
</td>
</tr>
<tr>
<td style="text-align:left;">
EDUCP_A: Medium Edu (vs Low Edu)
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.896
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
EDUCP_A: High Edu (vs Low Edu)
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.725
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
LSATIS4_A: Dissatisfied (vs Satisfied)
</td>
<td style="text-align:right;">
0.830
</td>
<td style="text-align:right;">
0.884
</td>
<td style="text-align:right;">
6.5
</td>
</tr>
<tr>
<td style="text-align:left;">
PHSTAT_A: Fair/Poor Health (vs Good Health)
</td>
<td style="text-align:right;">
2.049
</td>
<td style="text-align:right;">
2.004
</td>
<td style="text-align:right;">
-2.2
</td>
</tr>
<tr>
<td style="text-align:left;">
CHLEV_A: High Cholesterol (Yes)
</td>
<td style="text-align:right;">
2.279
</td>
<td style="text-align:right;">
2.107
</td>
<td style="text-align:right;">
-7.5
</td>
</tr>
<tr>
<td style="text-align:left;">
HYPEV_A: Hypertension (Yes)
</td>
<td style="text-align:right;">
2.711
</td>
<td style="text-align:right;">
2.128
</td>
<td style="text-align:right;">
-21.5
</td>
</tr>
<tr>
<td style="text-align:left;">
LIVEREV_A: Liver Disease (Yes)
</td>
<td style="text-align:right;">
1.885
</td>
<td style="text-align:right;">
1.928
</td>
<td style="text-align:right;">
2.2
</td>
</tr>
<tr>
<td style="text-align:left;">
STREV_A: Stroke (Yes)
</td>
<td style="text-align:right;">
1.096
</td>
<td style="text-align:right;">
1.112
</td>
<td style="text-align:right;">
1.4
</td>
</tr>
<tr>
<td style="text-align:left;">
MIEV_A: Myocardial Infarction (Yes)
</td>
<td style="text-align:right;">
1.365
</td>
<td style="text-align:right;">
1.329
</td>
<td style="text-align:right;">
-2.6
</td>
</tr>
<tr>
<td style="text-align:left;">
ANGEV_A: Angina (Yes)
</td>
<td style="text-align:right;">
1.037
</td>
<td style="text-align:right;">
1.008
</td>
<td style="text-align:right;">
-2.8
</td>
</tr>
<tr>
<td style="text-align:left;">
CHDEV_A: CHD (Yes)
</td>
<td style="text-align:right;">
1.380
</td>
<td style="text-align:right;">
1.258
</td>
<td style="text-align:right;">
-8.9
</td>
</tr>
<tr>
<td style="text-align:left;">
DEPEV_A: Depression (Yes)
</td>
<td style="text-align:right;">
1.128
</td>
<td style="text-align:right;">
1.175
</td>
<td style="text-align:right;">
4.2
</td>
</tr>
<tr>
<td style="text-align:left;">
ANXEV_A: Anxiety (Yes)
</td>
<td style="text-align:right;">
0.830
</td>
<td style="text-align:right;">
0.921
</td>
<td style="text-align:right;">
10.9
</td>
</tr>
<tr>
<td style="text-align:left;">
SMKEV_A: Smoker (Yes)
</td>
<td style="text-align:right;">
0.980
</td>
<td style="text-align:right;">
0.916
</td>
<td style="text-align:right;">
-6.5
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Rarely Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
0.975
</td>
<td style="text-align:right;">
1.042
</td>
<td style="text-align:right;">
6.9
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Sometimes Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
1.015
</td>
<td style="text-align:right;">
1.071
</td>
<td style="text-align:right;">
5.5
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Usually Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
0.804
</td>
<td style="text-align:right;">
0.835
</td>
<td style="text-align:right;">
3.8
</td>
</tr>
<tr>
<td style="text-align:left;">
LONELY_A: Always Lonely (vs Never Lonely)
</td>
<td style="text-align:right;">
1.133
</td>
<td style="text-align:right;">
1.162
</td>
<td style="text-align:right;">
2.6
</td>
</tr>
</tbody>
</table>
<p>Make a plot showing the comparison.</p>
<pre class="r"><code>compare_table |&gt;
  filter(!is.na(OR_noconf), !is.na(OR_full)) |&gt;
  mutate(
    big_change = ifelse(abs(OR_change_pct) &gt;= 10, &quot;&gt;= 10%&quot;, &quot;&lt; 10%&quot;)
  ) |&gt;
  ggplot(aes(x = Term, y = OR_change_pct, fill = big_change)) +
  geom_col() +
  geom_hline(yintercept = 0, linetype = &quot;dashed&quot;) +
  coord_flip() +
  scale_fill_manual(values = c(&quot;&lt; 10%&quot; = &quot;grey80&quot;, &quot;&gt;= 10%&quot; = &quot;tomato&quot;)) +
  labs(
    title = &quot;% Change in OR After Adjusting for Confounders&quot;,
    x = &quot;Predictor Term&quot;,
    y = &quot;% Change in OR (Full vs. Reduced Model)&quot;,
    fill = &quot;Absolute change&quot;
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = &quot;bold&quot;),
    legend.position = &quot;bottom&quot;
  )</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>When comparing models with and without adjustment for the
prespecified confounders (age, sex, BMI, and education), most predictors
show relatively small changes in their odds ratios (ORs), generally
within ±10% (e.g., life satisfaction, self-rated health, high
cholesterol, liver disease, stroke, myocardial infarction, angina, CHD,
depression, smoking, and loneliness). This suggests that these
associations are fairly robust to adjustment for demographic and
anthropometric factors.</p>
<p>In contrast, the ORs for mobility difficulty (DIFF_A) and
hypertension (HYPEV_A) are noticeably attenuated after adjustment: the
ORs for different levels of walking difficulty decrease by about 16–19%,
and the OR for hypertension decreases by about 22%, indicating
meaningful confounding by age, sex, BMI, and education. For anxiety
(ANXEV_A), the OR moves toward the null by around 11%, suggesting that
the apparent protective association in the unadjusted model is partly
explained by confounding. Overall, these results support treating
demographic and BMI-related variables as important confounders,
particularly for mobility difficulty and hypertension in relation to
diabetes risk.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
