---
title: "cleaning"
author: "Yirou Hu"
date: "2025-11-20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## cleaning dataset
```{r}
library(tidyverse)
library(readxl)
library(dplyr)
```

```{r}
nhis24_df = read_excel("adults_2024.xlsx") |>
  select(-REGION) |>
  # Dealing with outcome variable
  mutate(
    # DIBEV_A
    Diabetes = case_when(
      DIBEV_A == 1 ~ 1,  
      DIBEV_A == 2 ~ 0,  
      TRUE ~ DIBEV_A 
    )
  ) |>
  filter(!Diabetes %in% c(7, 8, 9)) |>
  # Dealing with covariates
  mutate(
    # BMI
    BMI_Recoded = case_when(
      BMICATD_A == 1 ~ 1,  # Underweight -> 1
      BMICATD_A == 2 ~ 0,  # Healthy weight -> 0
      BMICATD_A == 3 ~ 2,  # Overweight -> 2
      BMICATD_A %in% c(4, 5, 6) ~ 3,  # Class 1, 2, 3 Obesity -> 3
      TRUE ~ BMICATD_A 
    )
  ) |>
  filter(BMI_Recoded != 9) |>
  mutate(
    # Difficulty in walking
    DIFF_Recoded = case_when(
      DIFF_A == 1 ~ 0,  # No difficulty -> 0
      DIFF_A == 2 ~ 1,  # Some difficulty -> 1
      DIFF_A == 3 ~ 2,  # A lot of difficulty -> 2
      DIFF_A == 4 ~ 3,  # Cannot do at all -> 3
      TRUE ~ DIFF_A 
    )
  ) |>
  filter(!DIFF_Recoded %in% c(7, 8, 9)) |>
  mutate(
    # Education
    EDUC_Recoded = case_when(
      EDUCP_A %in% c(00, 01, 02, 03, 04) ~ 0,
      EDUCP_A %in% c(05, 06, 07) ~ 1,
      EDUCP_A %in% c(08, 09, 10) ~ 2,
      TRUE ~ EDUCP_A 
    )
  ) |>
  filter(!EDUC_Recoded %in% c(97, 98, 99)) |> 
  mutate(
    # Life satisfaction
    LSATIS4_Recoded = case_when(
      LSATIS4_A %in% c(1, 2) ~ 0,  # Very satisfied, Satisfied -> 0
      LSATIS4_A %in% c(3, 4) ~ 1,  # Dissatisfied, Very dissatisfied -> 1
      TRUE ~ LSATIS4_A 
    )
  ) |>
  filter(!LSATIS4_Recoded %in% c(7, 8, 9)) |>
  mutate(
    # Health status
    PHSTAT_Recoded = case_when(
      PHSTAT_A %in% c(1, 2, 3) ~ 0,  # Excellent, Very good, Good -> 0
      PHSTAT_A %in% c(4, 5) ~ 1,  # Fair, Poor -> 1
      TRUE ~ PHSTAT_A 
    )
  ) |>
  filter(!PHSTAT_Recoded %in% c(7, 8, 9)) |> 
  mutate(
    # Cholesterol 
    CHLEV_Recoded = case_when(
      CHLEV_A == 2 ~ 0,  # never had high cholesterol -> 0
      CHLEV_A == 1 ~ 1,  # had high cholesterol -> 1
      TRUE ~ CHLEV_A 
    )
  ) |>
  filter(!CHLEV_Recoded %in% c(7, 8, 9)) |> 
  mutate(
    # Hypertension
    HYP_Recoded = case_when(
      HYPEV_A == 1 ~ 1,   # Yes hypertension -> 1
      HYPEV_A == 2 ~ 0,   # No hypertension -> 0
      TRUE ~ HYPEV_A)) |>
  filter(!HYP_Recoded %in% c(7, 8, 9)) |>
  mutate(
    # Cirrhosis or liver condition
    LIVER_Recoded = case_when(
      LIVEREV_A == 1 ~ 1,   # Yes -> 1
      LIVEREV_A == 2 ~ 0,   # No -> 0
      TRUE ~ LIVEREV_A)) |>
  filter(!LIVER_Recoded %in% c(7, 8, 9)) |> 
  mutate(
    # Stroke
    STROKE_Recoded = case_when(
      STREV_A == 1 ~ 1,   # Yes stroke -> 1
      STREV_A == 2 ~ 0,   # No stroke -> 0
      TRUE ~ STREV_A)) |>
  filter(!STROKE_Recoded %in% c(7, 8, 9))|>
  mutate(
    # Recode MIEV_A
    MIEV_A_recoded = case_when(
      MIEV_A == 1 ~ 1,
      MIEV_A == 2 ~ 0,
      TRUE ~ NA_real_
    ),
    
    # Recode ANGEV_A
    ANGEV_A_recoded = case_when(
      ANGEV_A == 1 ~ 1,
      ANGEV_A == 2 ~ 0,
      TRUE ~ NA_real_
    ),
    
    # Recode CHDEV_A
    CHDEV_A_recoded = case_when(
      CHDEV_A == 1 ~ 1,
      CHDEV_A == 2 ~ 0,
      TRUE ~ NA_real_
    )
  ) |>
  
  # Delete rows where any recoded variable became NA (invalid values like 7/8/9/etc)
  filter(
    !is.na(MIEV_A_recoded),
    !is.na(ANGEV_A_recoded),
    !is.na(CHDEV_A_recoded)
  ) |>
  
  # cleaning Refused / Not ascertained / Don't know columns in Depression, Anxiety, Smoking, Lonelyness
  filter(
    LONELY_A != 7 & LONELY_A != 8 & LONELY_A != 9,
    SMKEV_A  != 7 & SMKEV_A  != 8 & SMKEV_A  != 9,
    DEPEV_A  != 7 & DEPEV_A  != 8 & DEPEV_A  != 9,
    ANXEV_A  != 7 & ANXEV_A  != 8 & ANXEV_A  != 9
  ) |>
  
  mutate(
    lonely = case_when(
      LONELY_A == 5 ~ 0,
      LONELY_A == 4 ~ 1,
      LONELY_A == 3 ~ 2,
      LONELY_A == 2 ~ 3,
      LONELY_A == 1 ~ 4,
    ),
    
    # Smoking: 1=yes, 2=no
    smoke = case_when(
      SMKEV_A == 1 ~ 1,
      SMKEV_A == 2 ~ 0
    ),
    
    # Depression: 1=yes, 2=no
    depression = case_when(
      DEPEV_A == 1 ~ 1,
      DEPEV_A == 2 ~ 0
    ),
    
    # Anxiety: 1=yes, 2=no
    anxiety = case_when(
      ANXEV_A == 1 ~ 1,
      ANXEV_A == 2 ~ 0
    )
  )

  
  
```


